export const incomeCategories = [
  'SPP',
  'Uang Pangkal',
  'Donasi',
  'Dana BOS',
  'Uang Pendaftaran',
  'Uang Seragam',
  'Uang Buku',
  'Penjualan Barang',
  'Hibah',
  'Sponsorship',
  'Uang Kegiatan',
  'Uang Ujian',
  'Pendapatan Lainnya',
]

export const expenseCategories = [
  'Gaji Guru',
  'Gaji Staff',
  'Operasional Sekolah',
  'Pembelian ATK',
  'Listrik',
  'Air',
  'Internet',
  'Pemeliharaan Gedung',
  'Kegiatan Siswa',
  'Transportasi',
  'Pembelian Seragam',
  'Pembelian Buku',
  'Honor Narasumber',
  'Pengembangan Kurikulum',
  'Pelatihan Guru',
  'Asuransi',
  'Perizinan',
  'Pajak',
  'Pengeluaran Lainnya',
]
